env: "local"
forumPath: "postgres://postgres:1@host.docker.internal:5555/forum?sslmode=disable"
authPath: "postgres://postgres:1@host.docker.internal:5555/auth?sslmode=disable"


grpc:
  port: 50051
  timeout: 10h

http:
  port: 8080

gateway:
  port: 8090

auth_service:
  port: 50053


forum_service:
  port: 50052

chat:
  message_lifetime: 600s
  max_message_length: 1000
  cleanup_interval: 300s
  allowed_origins:
    - "localhost:3000"
    - "your-production-domain.com"

logger:
  level: "debug"
  format: "text"

auth:
  jwt_secret: "asaslfmas"
  access_token_ttl: 600s   # 10 минут
  refresh_token_ttl: 720h # 30 дней