database:
  host: "localhost"
  port: 5555
  user: "auth_user"
  password: "1"
  name: "auth_db"
  sslmode: "disable"

jwt:
  secret_key: "your_very_secret_key_here"
  access_token_ttl: 15m
  refresh_token_ttl: 720h # 30 дней